apiVersion: v2
name: kong-guard-ai
description: Kong Gateway with Kong Guard AI security plugin for enterprise production deployments
type: application
version: 1.0.0
appVersion: "3.4.2"
home: https://github.com/kong/kong-guard-ai
sources:
  - https://github.com/kong/kong-guard-ai
keywords:
  - kong
  - api-gateway
  - security
  - ai
  - threat-detection
maintainers:
  - name: Kong Guard AI Team
    email: kong-guard-ai@kong.com
icon: https://raw.githubusercontent.com/kong/kong-guard-ai/main/docs/logo.png
annotations:
  category: Security
  licenses: Apache-2.0
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 23.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled