version: '3.8'

networks:
  kongguard-network:
    driver: bridge

services:
  kongguard-ai:
    build: .
    container_name: kongguard-ai-app
    ports:
      - "5000:5000"  # AI Service
      - "8080:8080"  # Dashboard
    environment:
      - PYTHONPATH=/app
      - SUPABASE_HOST=192.168.0.225
      - SUPABASE_DATABASE=postgres
      - SUPABASE_USER=postgres
      - SUPABASE_PASSWORD=postgres
      - SUPABASE_PORT=5432
      - KONG_ADMIN_URL=http://192.168.0.202:18001
      - AI_SERVICE_PORT=5000
      - DASHBOARD_PORT=8080
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - kongguard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  kongguard-data:
  kongguard-logs: