# Prometheus Configuration for Kong Guard AI
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'kong-guard-ai-production'
    environment: 'production'

rule_files:
  - "/etc/prometheus/alerts.yml"
  - "/etc/prometheus/kong-guard-ai-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

scrape_configs:
  # Kong Gateway Metrics
  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong-gateway:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # Kong Guard AI Plugin Metrics
  - job_name: 'kong-guard-ai-plugin'
    static_configs:
      - targets: ['kong-gateway:8100']
    metrics_path: '/kong-guard-ai/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s
    honor_labels: true

  # Kong Admin API Health
  - job_name: 'kong-admin-health'
    static_configs:
      - targets: ['kong-gateway:8001']
    metrics_path: '/status'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Node Exporter for Host Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Redis Metrics (if enabled)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Elasticsearch Metrics
  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  # Kubernetes Pod Discovery
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - kong-guard-ai
            - monitoring
    relabel_configs:
      # Only scrape pods with prometheus.io/scrape annotation
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      # Use custom path if specified
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      # Use custom port if specified
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      # Add pod metadata as labels
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # Kubernetes Service Discovery
  - job_name: 'kubernetes-services'
    kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
            - kong-guard-ai
            - monitoring
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_service_name

# Remote write configuration (for long-term storage)
remote_write:
  - url: "https://your-remote-prometheus-endpoint/api/v1/write"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'kong_guard_ai_.*|kong_.*|up|prometheus_.*'
        action: keep
