_format_version: "3.0"
_transform: true

# ====================
# Services
# ====================
services:
  # HTTPBin Service - Testing HTTP methods
  - name: httpbin-service
    url: http://httpbin:80
    retries: 5
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - testing
      - http
    routes:
      - name: httpbin-route
        paths:
          - /httpbin
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        tags:
          - testing
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600

  # Echo Server - For testing requests/responses
  - name: echo-service
    url: http://echo-server:80
    tags:
      - testing
      - echo
    routes:
      - name: echo-route
        paths:
          - /echo
        strip_path: true
        tags:
          - testing
    plugins:
      - name: request-transformer
        config:
          add:
            headers:
              - X-Kong-Proxy:true
              - X-Service:echo

  # MockBin Service - For mocking APIs
  - name: mockbin-service
    url: http://mockbin:8080
    tags:
      - testing
      - mock
    routes:
      - name: mockbin-route
        paths:
          - /mock
        strip_path: true
        tags:
          - testing

  # Admin API Proxy (Read-only)
  - name: admin-api-proxy
    url: http://kong-gateway-db:8001
    tags:
      - admin
      - internal
    routes:
      - name: admin-route
        paths:
          - /admin-api
        strip_path: true
        methods:
          - GET
        tags:
          - admin
    plugins:
      - name: ip-restriction
        config:
          allow:
            - 172.20.0.0/16
            - 127.0.0.1
            - ::1

# ====================
# Global Plugins
# ====================
plugins:
  # Rate Limiting
  - name: rate-limiting
    config:
      minute: 100
      hour: 10000
      policy: local
      fault_tolerant: true
      hide_client_headers: false
      redis_ssl: false
      redis_ssl_verify: false
    tags:
      - global
      - rate-limit

  # Request Size Limiting
  - name: request-size-limiting
    config:
      allowed_payload_size: 10
      size_unit: megabytes
      require_content_length: false
    tags:
      - global
      - security

  # Correlation ID
  - name: correlation-id
    config:
      header_name: X-Kong-Request-Id
      generator: uuid
      echo_downstream: true
    tags:
      - global
      - observability

  # Prometheus Metrics
  - name: prometheus
    tags:
      - global
      - monitoring

# ====================
# Consumers
# ====================
consumers:
  # Test User with API Key
  - username: test-user
    custom_id: test-001
    tags:
      - testing
    keyauth_credentials:
      - key: test-api-key-123

  # Admin User with API Key
  - username: admin-user
    custom_id: admin-001
    tags:
      - admin
    keyauth_credentials:
      - key: admin-api-key-xyz
    acls:
      - group: admin

  # Premium User with JWT
  - username: premium-user
    custom_id: premium-001
    tags:
      - premium
    jwt_secrets:
      - key: premium-jwt-key
        secret: "super-secret-jwt-key-for-testing"
        algorithm: HS256

# ====================
# Upstreams (Load Balancing)
# ====================
upstreams:
  - name: httpbin-upstream
    slots: 100
    tags:
      - load-balance
    targets:
      - target: httpbin:80
        weight: 100
    healthchecks:
      active:
        type: http
        http_path: /status/200
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 3
      passive:
        healthy:
          successes: 2
        unhealthy:
          http_failures: 3
          timeouts: 3

# ====================
# Certificates
# ====================
certificates:
  - cert: |
      -----BEGIN CERTIFICATE-----
      MIIDXTCCAkWgAwIBAgIJAKLdQVPy90WjMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
      BAYTAlVTMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
      aWRnaXRzIFB0eSBMdGQwHhcNMjQwMTAxMDAwMDAwWhcNMjUwMTAxMDAwMDAwWjBF
      MQswCQYDVQQGEwJVUzETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
      ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
      CgKCAQEAtest1234567890abcdefghijklmnopqrstuvwxyz1234567890test
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQtest123456789
      -----END PRIVATE KEY-----
    snis:
      - name: localhost
    tags:
      - testing