name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_call:

jobs:
  python-lint:
    name: Python Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run ruff check
        run: ruff check . --output-format=github

      - name: Run ruff format check
        run: ruff format --check .

      - name: Run mypy type checking
        run: mypy src/ --show-error-codes

      - name: Run bandit security check
        run: bandit -r src/ -f json -o bandit-report.json || true

      - name: Upload bandit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-results
          path: bandit-report.json

  lua-lint:
    name: Lua Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lua tools
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
          sudo luarocks install stylua

      - name: Run luacheck
        run: |
          luacheck kong-plugin/kong/plugins/kong-guard-ai/ \
            --config .luacheckrc \
            --formatter TAP

      - name: Run stylua format check
        run: |
          stylua --check kong-plugin/kong/plugins/kong-guard-ai/ \
            --config-path .stylua.toml

  dockerfile-lint:
    name: Dockerfile Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-color: true
          verbose: true

      - name: Upload hadolint results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif

  yaml-lint:
    name: YAML Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: |
          yamllint .github/workflows/ \
            -d "{extends: default, rules: {line-length: {max: 120}, comments-indentation: disable}}"

  shell-lint:
    name: Shell Script Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
          format: gcc
